### ISSUE TITLE
Images and SavedImages screen shows red screen when user doesn't have whatsapp installed

### ISSUE THREAD

**Issue by lordvidex** [Baksman/swhatsapp_status_saver#1]
<img width="339" alt="Screen Shot 2021-02-21 at 11 25 43 AM" src="https://user-images.githubusercontent.com/49334512/108619714-a5494d80-7437-11eb-8769-1838d893f1f9.png">

**Comment by Baksman** [comment]
Oops sorry will fix that nw

**Comment by lordvidex** [comment]
I have made a pull request already D:)
I just caught the error and returned an empty list for the imagesList.

**Comment by Baksman** [comment]
thanks merged
